USE [master]
GO

/****** Object:  Database [ContactDB]    Script Date: 1/4/2021 7:01:23 PM ******/
CREATE DATABASE [ContactDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ContactDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.VULCAN\MSSQL\DATA\ContactDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ContactDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.VULCAN\MSSQL\DATA\ContactDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ContactDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ContactDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ContactDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ContactDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ContactDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ContactDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ContactDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ContactDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ContactDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ContactDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ContactDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ContactDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ContactDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ContactDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ContactDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ContactDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ContactDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ContactDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ContactDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ContactDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ContactDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ContactDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ContactDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ContactDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ContactDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ContactDB] SET  MULTI_USER 
GO

ALTER DATABASE [ContactDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ContactDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ContactDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ContactDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ContactDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ContactDB] SET QUERY_STORE = OFF
GO

USE [ContactDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ContactDB] SET  READ_WRITE 
GO


